name: hds_ptcl
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1 # Version and build number

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2 # For storing user preferences locally
  permission_handler: ^11.3.0 # Requesting permissions on both iOS and Android
  dio: ^5.4.2+1 # For API handling
  webview_flutter: ^4.5.0 # For displaying web content within the app
  line_icons: ^2.0.3 # Icon set for the app
  fluttertoast: ^8.2.12 # For showing toast notifications
  connectivity_plus: ^5.0.2 # Checking internet connectivity
  flutter_svg: ^2.0.10 # Handling SVGs and animated splash screen
  get: ^4.6.6 # State management
  dropdown_button2: ^2.3.9 # Dropdown UI package
  audioplayers: ^5.2.1 # Playing audio from assets
  upgrader: ^9.0.0 # App version upgrade check
  flutter_lints: ^5.0.0 # Linting rules for better coding practices
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - images/